---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmChart
metadata:
  name: traefik
  namespace: traefik
spec:
  chart: traefik
  repo: https://traefik.github.io/charts
  targetNamespace: traefik
  bootstrap: true
