apiVersion: v1
data:
    TOKEN: ENC[AES256_GCM,data:ZuBNENSsnrQ=,iv:YmviVMjNBUKt5l+QV6p+of7fbT7CXWCbV8biRjQLjcE=,tag:JonEN7gyRSIujU4oBXrsPg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: basic-auth
    namespace: default
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-03-15T16:15:39Z"
    mac: ENC[AES256_GCM,data:0ld7BYJh14NLUg6EjsmtSov/uS2dj8VE9TgasSWhhNrqkrTA9cukejus15IUE7lYvZg2/NoRUY5Lp/Fw/PdtKDCmmu73JGfSXwwlVG4XtIuFlhQtyJKbcR74287kay5efTj7gdFEoU2VnpJMPANB/rokdliB9syXFEFaoVeEYtI=,iv:ux+qqcoYJsGUzqMO1cAZ7rbxqSLDd7RHTy50S0ijxyU=,tag:EtNEV9AQnp9dpVooW2ymrg==,type:str]
    pgp:
        - created_at: "2024-03-15T16:15:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DX+bAkBckFqQSAQdAJlMAMrDb+J4T2YyJZyOPXgJvLQwqItabxxFnwQfHnEow
            qD19s1STbKCn1Df7Zp8JMESN8qJYUSfRiJfan6eExaqxBV+nmiQaitKAv4mJwkBE
            1GgBCQIQf4jddDIFzavv1cRdclKCmd8vDuhNp6J2B4LpfTpC+732wgz48sXd3LUa
            zQQsCjhe4IRkwHhg6QkOXsLy/tQeGoBPcL9xiUDPOgmGuF35n03OPRIsWNzabmug
            kBxNb6oD3jIjQA==
            =fBpw
            -----END PGP MESSAGE-----
          fp: 6C3BCD35DF04CE8A32871812068E9CB30A978247
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
