apiVersion: v1
data:
    password: ENC[AES256_GCM,data:+bc/AmU=,iv:OtYWVwwj8SqN5m+XQq+FrAsSUEF21JpwPCXGVURnEdk=,tag:DU08+UEDtQgK9PPzmWKxvA==,type:str]
    user: ENC[AES256_GCM,data:8doHO5Q=,iv:J8EDlgFbv5b41MKVVErXaIz2+0gm/pqThMb9LF214/c=,tag:b7fdTdfqyiz3hum39EKbrA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: basic-auth
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-03-15T15:51:27Z"
    mac: ENC[AES256_GCM,data:RBifKXWF8VTJbXJNqWOhOwWID6zKQ96oMBG/11dv63Xey6U8aUtMz47oevaZwjcadyXBZFmnIki0iNPK8PBYKA7IR3z+QrUVCCpY1bxUWRbtRzHwYM3esCmXK4unQ2rP6XBzQUdFyCd1N1kWUh6CA2BqtJDvnm7YPIvfe8K+1hU=,iv:3mmVYVjryFlEJ27RdXMvm8Pdpp7v+naXrxy93v6EMCQ=,tag:zsOP48YMaY2cO3VUZdoMtA==,type:str]
    pgp:
        - created_at: "2024-03-15T15:51:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DX+bAkBckFqQSAQdAWKKYZXy1PIg7ZFdHCVIa1VKwkOfD1jXsk5wtDGbTzCMw
            nLILYHWSBlTjDdOyWtB3AmuMZRUOU+/0mhe8maVhQ6n/SxGudpV/iAe6KgTPJnn9
            1GYBCQIQrtRjxXb6ZeQarj+bOwJEoX9lIclgrUEFSsfLza7jvnfzFW8jE6nXft6r
            0tqVuTk5NE3YA4cqCXaiyjlSLAvlKy066DOoQkVRa3i8bTdOD/M4XiV0vOAuu/1l
            2ZccTRvldvs=
            =eShA
            -----END PGP MESSAGE-----
          fp: 6C3BCD35DF04CE8A32871812068E9CB30A978247
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
